package com.zolipe.communitycensus.util;

public class CensusConstants {
    public static final String TWITTER_KEY = "x2Y1jJeHclGulzUSnI3gj4S92";
    public static final String TWITTER_SECRET = "vqVano8DjIDowBxH286P02eWQKd7DCi35GZIBD1FNRJ8zaPSG8";

    public static final String BASE_URL                                     = "http://zovis.in/";
    public static final String LOGIN_URL                                    = "ul/login";
    public static final String REGISTER_URL                                 = "ur/registration";
    public static final String ADD_MEMBER_URL                               = "am/addmember";
    public static final String ADD_SUPERVISOR_URL                           =  "as/addsupervisor";
    public static final String GET_SUPERVISOR_LIST_URL                      = "sl/supervisorlist";
    public static final String FAMILY_HEADS_LIST_URL                        = "fh/familyhead";
    public static final String GET_STATES_URL                               = "state/statelist";
    public static final String GET_CITY_LIST_URL                            = "city/citylist";
    public static final String GET_RELATIONS_LIST_URL                       = "relation/relationlist";
    public static final String UPDATE_SUPERVISOR_INFO_URL                   = "us/updatesupervisor";
    public static final String UPDATE_ADMIN_INFO_URL                        = "ua/updateadmin";
    public static final String UPDATE_MEMBER_INFO_URL                       = "um/updatemember";
    public static final String SEND_TELEGRAM_URL                            = "tbatchmessage/tbmessage";
    public static final String FAMILY_HEADS_LIST_WITH_FAMILY_MEMBERS_URL    = "md/memberdetails";
    public static final String SEND_EMAIL_URL                               = "email/sendemail";
    public static final String GET_SUMMARY_URL                              = "overallmember/summary";
    public static final String GET_SUMMARY_BY_ZIPCODE_URL                   = "rmbylocation/location";
    public static final String GET_SUMMARY_DAYWISE_URL                      = "daywise/report";
    public static final String ADMIN_LOGIN_URL                              = "al/adminlogin";
    public static final String SEND_GROUP_TELEGRAM_URL                      = "telegram/groupmessage";
    public static final String UPDATE_MEMBER_URL                            = "um/updatemember";
    public static final String UPLOAD_OFFLINE_SUPERVISORS_URL               = "olsupervisor/bulksupervisor";
    public static final String UPLOAD_OFFLINE_MEMBERS_URL                   = "offline/bulkmembers";
    public static final String GET_HELPER_DATA_URL                          = "helper/tablelist";

    public static final String SUCCESS = "success";
    public static final String STATUS = "status";
    public static final String STATUS_CODE = "status_code";
    public static String loginType = "login_type";
    public static String firstName = "first_name";
    public static String lastName = "last_name";
    public static String gender = "gender";
    public static String dob = "dob";
    public static String phoneNumber = "phone_number";
    public static String emailId = "email";
    public static String address = "address";
    public static String zipcode = "zipcode";
    public static String userAvatar = "user_avatar";
    public static String imageType = "image_type";
    public static String isFamilyHead = "isfamily_head";
    public static String createdBy = "created_by";
    public static String userRole = "user_role";
    public static String city_id = "city_id";
    public static String state_id = "state_id";
    public static String country = "country";
    public static String isLoggedIn = "is_logged_in";
    public static String userid = "userid";
    public static String image_url = "image_url";
    public static String search_text = "search_text";
    public static String familyHeadId = "family_head_id";
    public static String relationshipId = "relationship_id";
    public static String aadhaar = "aadhar_number";
    public static String head_aadhar_number = "head_aadhar_number";
    public static String SEND_SMS_URL = "sms/sendsms";
    public static String member_id = "member_id";
    public static String supervisorId = "supervisor_id";
    public static String rolebased_user_id = "rolebased_user_id";
}
